title: Killed by Roblox
description: Killed by Roblox is the open source list of dead Roblox products, services, and devices. It serves as a tribute and memorial of beloved services and products killed by Roblox.
url: "https://killedbygoogle.com"
Roblox:
  username: killedbygoogle
  card: summary_large_image
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
exclude:
  - node_modules/
  - vendor/
  - Gemfile.lock